### ISSUE TITLE
Query params with spaces are not handled correctly

### ISSUE THREAD

**Issue by gfredericks** [myfreeweb/clj-http-fake#26]
Query params with spaces do not match the way they're supposed to.

Failing test [here](https://github.com/gfredericks/clj-http-fake/commit/fee5e851952d9d2150511d02eefc5a03388c83df).

I think the best fix would be to stop doing string comparisons to match query strings, and instead parse requests as much as possible so we can do data comparisons and not worry about different ways of encoding things.

A short term fix could be something like [this](https://github.com/gfredericks/clj-http-fake/commit/37e38b425ef82592e1fffa31fe1feb02cb4e2986), but that might also break other things.

**Comment by myfreeweb** [comment]
Hi! Can you send a pull request with a fix? I haven't used Clojure in years, I'm not actively developing this project.

**Comment by gfredericks** [comment]
Probably!

**Comment by gfredericks** [comment]
Created #27
