### ISSUE TITLE
is it possible to validate headers with fake routes?

### ISSUE THREAD

**Issue by rushabhdotshah** [myfreeweb/clj-http-fake#28]

**Comment by myfreeweb** [comment]
Validate headers??

**Comment by amirci** [comment]
I think @rushabhdotshah may mean to specify not only the route but also the headers that need to match

Something like `(with-fake-routes {{:url url-to-match :headers headers-to-match} (fn [request].....)})`

**Comment by Jeiwan** [comment]
This can be done inside the `fn` passed to `with-fake-routes`. The function receives a request which you can parse, check and return different responses depending on request parameters.
