### ISSUE TITLE
Query strings with many params drastically increase runtime

### ISSUE THREAD

**Issue by matrix10657** [myfreeweb/clj-http-fake#37]
First off, great library; it's made my life significantly easier. So I thought that I'd combine it with quick check.

I'm testing an API that takes at least 6 different parameters, sometimes more depending on the particular testing scenario, and I noticed that my test runtimes would increase dramatically, and to the point where they simply wouldn't terminate. 

I eventually traced this back to the number of query parameters the API under test was producing. The long and short of it is, as I'm sure you're aware, that `potential-query-strings-for` combined with the `cartesian-product` function produce something like N! address-strings which were then being matched on, where N is the number of query parameters.

Here is a test to demonstrate the issue (it takes an extremely long time to complete):
```
(deftest matches-many-qparams
  (let [num-qparams 10]
    (is (= (with-fake-routes
             {#"http://test/\?.*"
              (fn [request]
                {:status 200 :headers {} :body "29RQPV"})}
             (:body (http/request
                      {:uri "http://test/"
                       :query-params (zipmap (map str (range 0 num-qparams))
                                             (range 0 num-qparams))
                       :method :get})))
           "29RQPV"))))
```

Also, since all the default implementations of RouteMatcher eventually delegate to the Pattern impl, they all suffer from this problem.

Of course, the workaround is to just supply my own implementation, but I feel like there's an opportunity to help my fellow users out.

-------

I was curious if you would be open to a PR which:
1. Improved string matching performance by reordering query params in a deterministic fashion. This should be doable for both `address` and `request`
2. Extended the default Pattern implementation to first compute an address-string with deterministically ordered query params, and if matching failed, only then attempt to match with the whole set of address-strings. The idea is that it's not possible to rearrange `address`, but by eagerly producing an `address-string` we may be able to match quickly. In a similar vein, making `potential-query-strings-for` lazy may accomplish the same thing
3. (I haven't thought much about the map case, yet)

**Comment by myfreeweb** [comment]
Wow, the little library I made in 2012-2014 and barely updated since is still useful to people!

> as I'm sure you're aware

I'm not — I haven't looked at this code, or any Clojure code really, for a *really* long time.

Of course I'm open to a PR. Also to adding you as a collaborator :)

**Comment by matrix10657** [comment]
Thanks for the quick follow-up, despite not touching the repo in so long :)
