### ISSUE TITLE
Non-string response bodies don't work

### ISSUE THREAD

**Issue by bfontaine** [myfreeweb/clj-http-fake#42]
I’m trying to test some code that looks like this:
```clojure
(c/get
  "http://example.com"
  {:async?             true
   :as                 :transit+msgpack
   :accept             :transit+msgpack}
  (fn [r]
    ;; do something with (:body r), a map
    )
  (fn [e]
    ;; ...
    ))
```
It relies on `clj-http`’s `:as` key to parse the response as `transit+msgpack` and pass the result to the response function. However, `clj-http.fake` thinks the body is always a string:
```
                      clj-http.fake/handle-request-for-route                 fake.clj:  163
                                    clj-http.fake/body-bytes                 fake.clj:  144
                                    clj-http.fake/utf8-bytes                 fake.clj:  127
java.lang.ClassCastException: clojure.lang.PersistentVector cannot be cast to java.lang.String
```

`clj-http.fake` should only do this bytes thing if the body is a string.

I can make a PR for this later.

**Comment by kawas44** [comment]
I think this may not be a valid issue.

Http-fake only fakes the ```clj-http.core/request``` function which is not responsible for the output  coercion. In fact, coercion is handled by a middleware wrapping the request for ```clj-http.client/get```.

So ```clj-http.core/request``` does indeed usually respond with a byte array, and if we need coercion we have to properly write an output matching the document we should get out of ```clj-http.core/request```

You can test this behaviour with other coercion options like ```:as byte-arrray```, ```:as "UTF-16"``` or ```:as :clojure```
